apiVersion: v1
kind: Secret
metadata:
  name: mongo-secret
  namespace: chat-app
type: Opaque
stringData:
  username: root
  password: admin
  mongo-uri: mongodb://root:admin@mongo-service:27017/chatApp?authSource=admin&retryWrites=true&w=majority
